[package]
name = "goeff_server"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
hell_core.workspace = true
hell_mod_openai.workspace = true

axum.workspace = true
dotenv.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
